### ISSUE TITLE
MicroKernel Sf 3.0 

### ISSUE THREAD

**Issue by maitrepylos** [fferriere/PommFosUserBundle#1]
Bonjour, je voudrais utiliser votre librairie sur Sf 3.0, mais j'ai une série d'erreur liès je pense à   "friendsofsymfony/user-bundle": "~1.3" .
Voici le type d'erreur : 

 Problem 1
    - Conclusion: remove symfony/symfony v3.0.3
    - Conclusion: don't install symfony/symfony v3.0.3
    - fferriere/pomm-project-fos-user-bundle 2.0.0 requires friendsofsymfony/user-bundle ~1.3 -> satisfiable by friendsofsymfony/user-bundle[v1.3.0, v1.3.1, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6].
    - fferriere/pomm-project-fos-user-bundle 2.0.1 requires friendsofsymfony/user-bundle ~1.3 -> satisfiable by friendsofsymfony/user-bundle[v1.3.0, v1.3.1, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6].
    - friendsofsymfony/user-bundle v1.3.0 requires symfony/security-bundle 2.1.\* -> satisfiable by symfony/security-bundle[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9].

Merci de votre aide.

**Comment by fferriere** [comment]
Bonjour,

Tout d'abord, merci pour l’intérêt que vous portez à la librairie.
Le FOSUserBundle n'est surement pas compatible avec Sf3 (en tout cas en version stable à ce jour).
Je ne sais quoi vous conseiller d'autre hormis de passer sur Sf2.8 ou d'abandonner l'idée d'utiliser FOSUserBundle :S 

Je reste ouvert à toute proposition de solution.

**Comment by maitrepylos** [comment]
Es-t-il possible de passer sur une version non Stable, ou connaissez-vous une autre lib d'auth que je peux mettre en place facilement avec POMM ?

**Comment by fferriere** [comment]
J'ai pas fait les tests pour utiliser la lib avec la version non stable de FosUserBundle. Mais dans l'idée ça pourrait se faire. La version 2-alpha de FOSUserBundle est-elle compatible Sf3 ?
Sinon je viens de voir que @vibby avait forker la lib : https://github.com/vibby/PommFosUserBundle et fait des modifications ça peut peut être vous intéresser.

**Comment by maitrepylos** [comment]
Merci, je vais jeter un oeil.
